services:

  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: "2g"
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/localhost/4444"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 15s
      

  automation:
    build: .
    container_name: selenium-tests
    depends_on:
      chrome:
        condition: service_healthy
    environment:
      - CHROME_HOST=chrome
    volumes:
      - ./target/allure-results:/app/target/allure-results
      - ./target/allure-report:/app/target/allure-report
      - ./target/screenshots:/app/target/screenshots
      - ./logs:/app/logs
