# To execute this docker compose yml file use `docker compose -f dc-hub.yml up`
# Add the `-d` flag at the end for detached execution
services:
  chrome:
    image: selenium/node-chrome:4.37.0
    platform: linux/amd64
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub


  edge:
    image: selenium/node-edge:4.37.0
    platform: linux/amd64
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub

  selenium-hub:
    image: selenium/hub:4.37.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/localhost/4444"]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 60s

  automation:
    build: .
    container_name: selenium-tests
    depends_on:
      selenium-hub:
        condition: service_healthy
    volumes:
      - ./target/allure-results:/app/target/allure-results
      - ./target/allure-report:/app/target/allure-report
      - ./target/screenshots:/app/target/screenshots
      - ./logs:/app/logs
